# Generated by Django 4.1.1 on 2022-12-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellpost',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sellpost',
            name='contact',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sellpost',
            name='description',
            field=models.TextField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='sellpost',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
